kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: startup-test-admin
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list"]
